name: CI

on: [push, pull_request]

jobs:
  lint-and-typehint:
    name: Lint and type hints
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Lint
        run: |
            flake8 .

      - name: Types
        run: |
            mypy --strict .
